= Dumper: Silence
:author: Philip Michael Raab
:email: <peep@inane.co.za>
:revnumber: 1.13.1
:revdate: 2023-05-26
:experimental:
:icons: font
:source-highlighter: highlight.js
:toc: auto

You can use the `\Inane\Dumper\Silence` attribute to silence dumps, silence a specified number of dumps, only show a specified number of dumps then go silent, per *class*, *method* or *function*. The Silence attribute also allows you to set Silence's initial state and then set a counter after which the state will toggle.

NOTE: If a class is silenced all functions are silenced regardless of their individual settings.

.Basic Silence Usage
[source,php]
----
use Inane\Dumper\Silence as DumperSilence;

#[DumperSilence()]
function doFirst(): void {
	echo 'hello', PHP_EOL;

	dd(__FUNCTION__, 'one');
	dd(__FUNCTION__, 'two');
}


#[DumperSilence(false)]
function doSecond(): void {
	echo 'hello', PHP_EOL;

	dd(__FUNCTION__, 'one');
	dd(__FUNCTION__, 'two');
}

doFirst(); // <1>
// hello

doSecond(); // <2>
// hello
// doSecond, one
// doSecond, two
----
<1> This only outputs the `echo`. The `dd`'s are ignored.
<2> Here the `echo` and `dd` output is displayed.

== Toggling State

This feature of Silence lets you either enable or disable dumping after a specified number of dump requests have been made. This lets you log only a few items when iterating over a large collection.

If you specify a limit, Silence's second parameter, the Silence instance will toggle its value after it has received that many check requests. i.e. Silent becomes verbose and vice versa.

NOTE: The toggle only happens once. *NOT* every time the limit is reached.

TIP: The is an issue logged to pass an array in place of an limit that sets when to toggle and how long the toggle should remain active.

.Toggle Silence Usage
[source,php]
----
use Inane\Dumper\Silence as DumperSilence;

#[DumperSilence(false, 1)]
function doFirst(): void {
	echo 'hello', PHP_EOL;

	dd(__FUNCTION__, 'one');
	dd(__FUNCTION__, 'two');
}


#[DumperSilence(true, 1)]
function doSecond(): void {
	echo 'hello', PHP_EOL;

	dd(__FUNCTION__, 'one');
	dd(__FUNCTION__, 'two');
}

doFirst(); // <1>
// hello
// doFirst, two

doSecond(); // <2>
// hello
// doSecond, one
----
<1> Now we have the `echo` and the value from the first `dd` request. Silence toggled *false* to *true* after *1* request so the second `dd` request was ignored.
<2> This is the reverse of the first. Here only the first `dd` request is shown.

== Advanced: Logging Silence checks

Actually geeky stuff would be a better way to describe this section. By default Silence checks are not shown in the Dumper panel but this can be enabled if you want to figure out why your toggles are not doing what you expect them to do.

To enable this this is one simple step, add `Type::Silence` to the `Dumper::$additionalTypes` array.

.Logging Silence Requests
[source,php]
----
Dumper::$additionalTypes[] = Type::Silence; // <1>
// code
Dumper::$additionalTypes = []; // <2>
----
<1> future Silence checks will be shown in the Dumper panel. 
<2> and Silence checks after this will no longer show in the Dumper panel.

=== Customising Silence checks

You can customise the Silence check logs per Silence instance to make them stand out from the rest by giving it a custom *label* and *colour*.

.Customising Silence Logs
[source,php]
----
#[Silence(on: true, config: [
	'label' => 'Do Test This', // <1>
	'colour' => 'purple', // <2>
])]
function doThis(): void {
	dd(null, 'Dump nothing important'); // <3>
}

doThis(); // <4>
doThis(); // <4>
doThis(); // <4>
----
<1> set custom label to appear in Dumper panel.
<2> set custom colour for log entry in Dumper panel.
<3> this will not be show due to Silence
<4> a purple entry labelled *Do Test This* will be added every time this function is called
